### ISSUE TITLE
Silencios de Armonia

### ISSUE THREAD

**Issue by Videxter** [essteban/CHmUsiCK#7]
La instruccion "spork~harm.sawOsc(["cm", "" ],2);", siendo harm un objeto de la clase Harmony, genera un error en consola:
[chuck](VM): NullPointerException: (array access) in shred[id=30:spork~exp], PC=[108]

No existen los silencios para los objetos de esta clase?

**Comment by essteban** [comment]
Harmony class now include silence, chmusick adopted the syntax you proposed. thanx!
